#!/bin/sh
#
# couchdb This is the init script for starting up the CouchDB server
#
# chkconfig: - 26 74
# description: Starts and stops the CouchDB daemon that handles \
#	       all database requests.

### BEGIN INIT INFO
# Provides: couchdb
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Should-Start: $remote_fs
# Should-Stop: $remote_fs
# Default-Start:
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: start and stop CouchDB database server
# Description: Apache CouchDB is a distributed, fault-tolerant and
#              schema-free document-oriented database accessible
#              via a RESTful HTTP/JSON API
### END INIT INFO

# this script can be used to run more than one couchdb service.
# to add a new couchdb service:
# export NAME=second
# ln -sf /etc/rc.d/init.d/couchdb /etc/rc.d/init.d/couchdb-$NAME
# - optionally create /etc/sysconfic/couchdb-$NAME
# - mkdir /var/{log,lib}/couchdb-$NAME
# - chown couchdb /var/{log,lib}/couchdb-$NAME
# - mkdir /etc/couchdb-$NAME
# - create /etc/couchdb-$NAME/local.ini and override e.g. the port
#   to make sure it can run side by side with the original couchdb


# Source function library.
. /etc/rc.d/init.d/functions

prog=couchdb
# get the service name from our current script name
# take into account possibly being run from /etc/rc*.d/[SK]*...
service=`basename $0 | sed 's/^[SK][0-9]*//g'`

exec=/usr/bin/$prog

# default values
COUCHDB_USER=couchdb
COUCHDB_STDOUT_FILE=/dev/null
COUCHDB_STDERR_FILE=/dev/null
COUCHDB_RESPAWN_TIMEOUT=0
COUCHDB_OPTIONS=
COUCHDB_CONFIG=

# customize configuration directory if the service is named differently
if test a$prog != $service
then
  DEFAULT=/etc/$service/default.ini
  if test ! -e $DEFAULT
  then
    DEFAULT=/etc/$prog/default.ini
  fi
  LOCAL=/etc/$service/local.ini
  if test ! -e $LOCAL
  then
    LOCAL=/etc/$prog/local.ini
  fi


  COUCHDB_CONFIG="-n -a $DEFAULT -a $LOCAL"
fi

[ -e /etc/sysconfig/$service ] && . /etc/sysconfig/$service

pidfile=/var/run/$prog/$service.pid
lockfile=/var/lock/subsys/$service

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $service: "
    rh_status_q && echo -n "already running" && warning && echo && exit 0
    daemon --user $COUCHDB_USER "$exec \
	-r $COUCHDB_RESPAWN_TIMEOUT \
	-o $COUCHDB_STDOUT_FILE \
	-e $COUCHDB_STDERR_FILE \
	-p $pidfile \
	$COUCHDB_OPTIONS $COUCHDB_CONFIG -b >/dev/null"
    retval=$?
    if test ! -e $pidfile
    then
      echo -n "$service did not start properly, check $COUCHDB_STDERR_FILE"
      failure
    fi
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $service: "
    retval=0
    if ! rh_status_q ; then
	echo -n "already stopped" && warning
    else
        daemon --user $COUCHDB_USER "$exec \
	  -p $pidfile \
          -d > /dev/null"
        retval=$?
    fi
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $pidfile $service
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart|force-reload)
        restart
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
